title: ICFI 2026
description: International Conference on Future Innovation (國際未來創新研討會)
baseurl: ""
url: https://icfi2026conf.github.io

permalink: pretty
remote_theme: piazzai/jekyll-nagymaros

home: /
copyright: International College, Providence University
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - demo/
  - docs/
  - jekyll-nagymaros.gemspec

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
